const buttonColors = {
  blue: {
    background: 'bg-blue-700',
    hover: 'hover:bg-blue-800',
    focus: 'focus:ring-blue-300',
    darkBackground: 'dark:bg-blue-600',
    darkHover: 'dark:hover:bg-blue-700',
    darkFocus: 'dark:focus:ring-blue-800',
    textColor: 'text-white',
    disabledColor: 'bg-blue-800',
  },
  gold: {
    background: 'bg-yellow-600',
    hover: 'hover:bg-yellow-700',
    focus: 'focus:ring-yellow-300',
    darkBackground: 'dark:bg-yellow-500',
    darkHover: 'dark:hover:bg-yellow-600',
    darkFocus: 'dark:focus:ring-yellow-800',
    textColor: 'text-white',
    disabledColor: 'bg-yellow-800',
  },
  red: {
    background: 'bg-red-600',
    hover: 'hover:bg-red-700',
    focus: 'focus:ring-red-300',
    darkBackground: 'dark:bg-red-500',
    darkHover: 'dark:hover:bg-red-600',
    darkFocus: 'dark:focus:ring-red-700',
    textColor: 'text-white',
    disabledColor: 'bg-red-700',
  },
  gray: {
    background: 'bg-gray-300',
    hover: 'hover:bg-gray-400',
    focus: 'focus:ring-gray-300',
    darkBackground: 'dark:bg-gray-400',
    darkHover: 'dark:hover:bg-gray-500',
    darkFocus: 'dark:focus:ring-gray-600',
    textColor: 'text-gray-700',
    disabledColor: 'bg-gray-400',
  },
  orange: {
    background: 'bg-orange-400',
    hover: 'hover:bg-orange-500',
    focus: 'focus:ring-orange-300',
    darkBackground: 'dark:bg-orange-600',
    darkHover: 'dark:hover:bg-orange-700',
    darkFocus: 'dark:focus:ring-orange-800',
    textColor: 'text-white',
    disabledColor: 'bg-orange-500',
  },
}

export default buttonColors